<!-- This file automatically generated by ParseAutoconfTexinfo utility -->
<!-- cvs -d:pserver:anonymous@sources.redhat.com:/cvs/eclipse \        -->
<!--   co autotools/ParseTexinfo                                       -->
<!DOCTYPE macros [

  <!ELEMENT macros (macro)*>

  <!ELEMENT macro (prototype*,synopsis)>
  <!ATTLIST macro
    id ID #REQUIRED
  >

  <!ELEMENT synopsis     (#PCDATA)*>

  <!ELEMENT prototype    (parameter+)?>

  <!ELEMENT parameter (#PCDATA)*>
  <!ATTLIST parameter
    content CDATA #REQUIRED
  >

]>

<macros>
  <macro id="AC_INIT">
      <prototype>
        <parameter content="unique-file-in-source-dir"/>
      </prototype>
        <synopsis>
          Process any command-line arguments and find the source code
         directory. &lt;VAR&gt;unique-file-in-source-dir&lt;/VAR&gt; is
         some file that is in the package's source directory;
         &lt;CODE&gt;configure&lt;/CODE&gt; checks for this file's
         existence to make sure that the directory that it is told
         contains the source code in fact does.  Occasionally people
         accidentally specify the wrong directory with
         &lt;samp&gt;--srcdir&lt;/samp&gt;; this is a safety check.  ,
         for more information.
        </synopsis>
  </macro>
  <macro id="AC_CONFIG_AUX_DIR">
      <prototype>
        <parameter content="dir"/>
      </prototype>
        <synopsis>
          Use the &lt;TT&gt;install-sh&lt;/TT&gt;,
         &lt;TT&gt;config.sub&lt;/TT&gt;,
         &lt;TT&gt;config.guess&lt;/TT&gt;, and Cygnus
         &lt;CODE&gt;configure&lt;/CODE&gt; scripts that are in directory
         &lt;VAR&gt;dir&lt;/VAR&gt;.  These are auxiliary files used in
         configuration.  &lt;VAR&gt;dir&lt;/VAR&gt; can be either
         absolute or relative to
         &lt;TT&gt;&lt;VAR&gt;srcdir&lt;/VAR&gt;&lt;/TT&gt;.  The default
         is &lt;TT&gt;&lt;VAR&gt;srcdir&lt;/VAR&gt;&lt;/TT&gt; or
         &lt;TT&gt;&lt;VAR&gt;srcdir&lt;/VAR&gt;/..&lt;/TT&gt; or
         &lt;TT&gt;&lt;VAR&gt;srcdir&lt;/VAR&gt;/../..&lt;/TT&gt;,
         whichever is the first that contains
         &lt;TT&gt;install-sh&lt;/TT&gt;.  The other files are not
         checked for, so that using
         &lt;CODE&gt;AC_PROG_INSTALL&lt;/CODE&gt; does not automatically
         require distributing the other auxiliary files.  It checks for
         &lt;TT&gt;install.sh&lt;/TT&gt; also, but that name is obsolete
         because some &lt;CODE&gt;make&lt;/CODE&gt; programs have a rule
         that creates &lt;TT&gt;install&lt;/TT&gt; from it if there is no
         &lt;TT&gt;Makefile&lt;/TT&gt;.
        </synopsis>
  </macro>
  <macro id="AC_OUTPUT">
      <prototype>
        <parameter content="[file... ["/>
        <parameter content="extra-cmds ["/>
        <parameter content="init-cmds]]]"/>
      </prototype>
        <synopsis>
          Create output files.  Call this macro once, at the end of
         &lt;TT&gt;configure.in&lt;/TT&gt;. The
         &lt;VAR&gt;file&lt;/VAR&gt;&lt;small&gt;...&lt;/small&gt;
         argument is a whitespace-separated list of output files; it may
         be empty.  This macro creates each file
         &lt;TT&gt;&lt;VAR&gt;file&lt;/VAR&gt;&lt;/TT&gt; by copying an
         input file (by default named
         &lt;TT&gt;&lt;VAR&gt;file&lt;/VAR&gt;.in&lt;/TT&gt;),
         substituting the output variable values. , for more information
         on using output variables. , for more information on creating
         them.  This macro creates the directory that the file is in if
         it doesn't exist (but not the parents of that directory). 
         Usually, &lt;TT&gt;Makefile&lt;/TT&gt;s are created this way,
         but other files, such as &lt;TT&gt;.gdbinit&lt;/TT&gt;, can be
         specified as well.&lt;/P&gt;&lt;P&gt;

         If &lt;CODE&gt;AC_CONFIG_HEADER&lt;/CODE&gt;,
         &lt;CODE&gt;AC_LINK_FILES&lt;/CODE&gt;, or
         &lt;CODE&gt;AC_CONFIG_SUBDIRS&lt;/CODE&gt; has been called, this
         macro also creates the files named as their arguments.&lt;/P&gt;&lt;P&gt;

         A typical call to &lt;CODE&gt;AC_OUTPUT&lt;/CODE&gt; looks like
         this:
         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; AC_OUTPUT(Makefile src/Makefile
         man/Makefile X/Imakefile)
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/P&gt;&lt;P&gt;

         You can override an input file name by appending to
         &lt;VAR&gt;file&lt;/VAR&gt; a colon-separated list of input
         files.  Examples:
         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; AC_OUTPUT(Makefile:templates/top.mk
         lib/Makefile:templates/lib.mk)
         AC_OUTPUT(Makefile:templates/vars.mk:Makefile.in:templates/rules.mk)
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt; Doing this
         allows you to keep your file names acceptable to MS-DOS, or to
         prepend and/or append boilerplate to the file.&lt;/P&gt;&lt;P&gt;

         If you pass &lt;VAR&gt;extra-cmds&lt;/VAR&gt;, those commands
         will be inserted into &lt;TT&gt;config.status&lt;/TT&gt; to be
         run after all its other processing.  If
         &lt;VAR&gt;init-cmds&lt;/VAR&gt; are given, they are inserted
         just before &lt;VAR&gt;extra-cmds&lt;/VAR&gt;, with shell
         variable, command, and backslash substitutions performed on them
         in &lt;CODE&gt;configure&lt;/CODE&gt;.  You can use
         &lt;VAR&gt;init-cmds&lt;/VAR&gt; to pass variables from
         &lt;CODE&gt;configure&lt;/CODE&gt; to the
         &lt;VAR&gt;extra-cmds&lt;/VAR&gt;.  If
         &lt;CODE&gt;AC_OUTPUT_COMMANDS&lt;/CODE&gt; has been called, the
         commands given to it are run just before the commands passed to
         this macro.
        </synopsis>
  </macro>
  <macro id="AC_OUTPUT_COMMANDS">
      <prototype>
        <parameter content="extra-cmds ["/>
        <parameter content="init-cmds]"/>
      </prototype>
        <synopsis>
         Specify additional shell commands to run at the end of
         &lt;TT&gt;config.status&lt;/TT&gt;, and shell commands to
         initialize any variables from
         &lt;CODE&gt;configure&lt;/CODE&gt;.  This macro may be called
         multiple times. Here is an unrealistic example:&lt;/P&gt;&lt;P&gt;

         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; fubar=27 AC_OUTPUT_COMMANDS([echo
         this is extra $fubar, and so on.], fubar=$fubar)
         AC_OUTPUT_COMMANDS([echo this is another, extra, bit], [echo
         init bit]) &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;
        </synopsis>
  </macro>
  <macro id="AC_PROG_MAKE_SET">
      <prototype>
      </prototype>
        <synopsis>
           If &lt;CODE&gt;make&lt;/CODE&gt; predefines the variable
         &lt;CODE&gt;MAKE&lt;/CODE&gt;, define output variable
         &lt;CODE&gt;SET_MAKE&lt;/CODE&gt; to be empty.  Otherwise,
         define &lt;CODE&gt;SET_MAKE&lt;/CODE&gt; to contain
         &lt;samp&gt;MAKE=make&lt;/samp&gt;.  Calls
         &lt;CODE&gt;AC_SUBST&lt;/CODE&gt; for
         &lt;CODE&gt;SET_MAKE&lt;/CODE&gt;.
        </synopsis>
  </macro>
  <macro id="AC_CONFIG_HEADER">
      <prototype>
        <parameter content="header-to-create ..."/>
      </prototype>
        <synopsis>
           Make &lt;CODE&gt;AC_OUTPUT&lt;/CODE&gt; create the file(s) in
         the whitespace-separated list
         &lt;VAR&gt;header-to-create&lt;/VAR&gt; containing C
         preprocessor &lt;CODE&gt;#define&lt;/CODE&gt; statements, and
         replace &lt;samp&gt;@@DEFS@@&lt;/samp&gt; in generated files
         with &lt;samp&gt;-DHAVE_CONFIG_H&lt;/samp&gt; instead of the
         value of &lt;CODE&gt;DEFS&lt;/CODE&gt;.  The usual name for
         &lt;VAR&gt;header-to-create&lt;/VAR&gt; is
         &lt;TT&gt;config.h&lt;/TT&gt;.&lt;/P&gt;&lt;P&gt;

         If &lt;VAR&gt;header-to-create&lt;/VAR&gt; already exists and
         its contents are identical to what
         &lt;CODE&gt;AC_OUTPUT&lt;/CODE&gt; would put in it, it is left
         alone.  Doing this allows some changes in configuration without
         needlessly causing object files that depend on the header file
         to be recompiled.&lt;/P&gt;&lt;P&gt;

         Usually the input file is named
         &lt;TT&gt;&lt;VAR&gt;header-to-create&lt;/VAR&gt;.in&lt;/TT&gt;;
         however, you can override the input file name by appending to
         &lt;VAR&gt;header-to-create&lt;/VAR&gt;, a colon-separated list
         of input files. Examples:
         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt;
         AC_CONFIG_HEADER(defines.h:defines.hin)
         AC_CONFIG_HEADER(defines.h:defs.pre:defines.h.in:defs.post)
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;  Doing this
         allows you to keep your file names acceptable to MS-DOS, or to
         prepend and/or append boilerplate to the file.
        </synopsis>
  </macro>
  <macro id="AC_CONFIG_SUBDIRS">
      <prototype>
        <parameter content="dir ..."/>
      </prototype>
        <synopsis>
           Make &lt;CODE&gt;AC_OUTPUT&lt;/CODE&gt; run
         &lt;CODE&gt;configure&lt;/CODE&gt; in each subdirectory
         &lt;VAR&gt;dir&lt;/VAR&gt; in the given whitespace-separated
         list.  If a given &lt;VAR&gt;dir&lt;/VAR&gt; is not found, no
         error is reported, so a &lt;CODE&gt;configure&lt;/CODE&gt;
         script can configure whichever parts of a large source tree are
         present.  If a given &lt;VAR&gt;dir&lt;/VAR&gt; contains
         &lt;TT&gt;configure.in&lt;/TT&gt; but no
         &lt;CODE&gt;configure&lt;/CODE&gt;, the Cygnus
         &lt;CODE&gt;configure&lt;/CODE&gt; script found by
         &lt;CODE&gt;AC_CONFIG_AUXDIR&lt;/CODE&gt; is used.&lt;/P&gt;&lt;P&gt;

         The subdirectory &lt;CODE&gt;configure&lt;/CODE&gt; scripts are
         given the same command line options that were given to this
         &lt;CODE&gt;configure&lt;/CODE&gt; script, with minor changes if
         needed (e.g., to adjust a relative path for the cache file or
         source directory).  This macro also sets the output variable
         &lt;CODE&gt;subdirs&lt;/CODE&gt; to the list of directories
         &lt;samp&gt;&lt;VAR&gt;dir&lt;/VAR&gt;
         &lt;small&gt;...&lt;/small&gt;&lt;/samp&gt;. 
         &lt;TT&gt;Makefile&lt;/TT&gt; rules can use this variable to
         determine which subdirectories to recurse into.  This macro may
         be called multiple times.
        </synopsis>
  </macro>
  <macro id="AC_PREFIX_DEFAULT">
      <prototype>
        <parameter content="prefix"/>
      </prototype>
        <synopsis>
         Set the default installation prefix to
         &lt;VAR&gt;prefix&lt;/VAR&gt; instead of
         &lt;TT&gt;/usr/local&lt;/TT&gt;.
        </synopsis>
  </macro>
  <macro id="AC_PREFIX_PROGRAM">
      <prototype>
        <parameter content="program"/>
      </prototype>
        <synopsis>
          If the user did not specify an installation prefix (using the
         &lt;samp&gt;--prefix&lt;/samp&gt; option), guess a value for it
         by looking for &lt;VAR&gt;program&lt;/VAR&gt; in
         &lt;CODE&gt;PATH&lt;/CODE&gt;, the way the shell does.  If
         &lt;VAR&gt;program&lt;/VAR&gt; is found, set the prefix to the
         parent of the directory containing
         &lt;VAR&gt;program&lt;/VAR&gt;; otherwise leave the prefix
         specified in &lt;TT&gt;Makefile.in&lt;/TT&gt; unchanged.  For
         example, if &lt;VAR&gt;program&lt;/VAR&gt; is
         &lt;CODE&gt;gcc&lt;/CODE&gt; and the
         &lt;CODE&gt;PATH&lt;/CODE&gt; contains
         &lt;TT&gt;/usr/local/gnu/bin/gcc&lt;/TT&gt;, set the prefix to
         &lt;TT&gt;/usr/local/gnu&lt;/TT&gt;.
        </synopsis>
  </macro>
  <macro id="AC_PREREQ">
      <prototype>
        <parameter content="version"/>
      </prototype>
        <synopsis>
          Ensure that a recent enough version of Autoconf is being used. 
         If the version of Autoconf being used to create
         &lt;CODE&gt;configure&lt;/CODE&gt; is earlier than
         &lt;VAR&gt;version&lt;/VAR&gt;, print an error message on the
         standard error output and do not create
         &lt;CODE&gt;configure&lt;/CODE&gt;.  For example:&lt;/P&gt;&lt;P&gt;

         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; AC_PREREQ(1.8)
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/P&gt;&lt;P&gt;

         This macro is useful if your &lt;TT&gt;configure.in&lt;/TT&gt;
         relies on non-obvious behavior that changed between Autoconf
         releases.  If it merely needs recently added macros, then
         &lt;CODE&gt;AC_PREREQ&lt;/CODE&gt; is less useful, because the
         &lt;CODE&gt;autoconf&lt;/CODE&gt; program already tells the user
         which macros are not found.  The same thing happens if
         &lt;TT&gt;configure.in&lt;/TT&gt; is processed by a version of
         Autoconf older than when &lt;CODE&gt;AC_PREREQ&lt;/CODE&gt; was
         added.
        </synopsis>
  </macro>
  <macro id="AC_REVISION">
      <prototype>
        <parameter content="revision-info"/>
      </prototype>
        <synopsis>
          Copy revision stamp &lt;VAR&gt;revision-info&lt;/VAR&gt; into
         the &lt;CODE&gt;configure&lt;/CODE&gt; script, with any dollar
         signs or double-quotes removed.  This macro lets you put a
         revision stamp from &lt;TT&gt;configure.in&lt;/TT&gt; into
         &lt;CODE&gt;configure&lt;/CODE&gt; without RCS or CVS changing
         it when you check in &lt;CODE&gt;configure&lt;/CODE&gt;.  That
         way, you can determine easily which revision of
         &lt;TT&gt;configure.in&lt;/TT&gt; a particular
         &lt;CODE&gt;configure&lt;/CODE&gt; corresponds to.&lt;/P&gt;&lt;P&gt;

         It is a good idea to call this macro before
         &lt;CODE&gt;AC_INIT&lt;/CODE&gt; so that the revision number is
         near the top of both &lt;TT&gt;configure.in&lt;/TT&gt; and
         &lt;CODE&gt;configure&lt;/CODE&gt;.  To support doing that, the
         &lt;CODE&gt;AC_REVISION&lt;/CODE&gt; output begins with
         &lt;samp&gt;#! /bin/sh&lt;/samp&gt;, like the normal start of a
         &lt;CODE&gt;configure&lt;/CODE&gt; script does.&lt;/P&gt;&lt;P&gt;

         For example, this line in &lt;TT&gt;configure.in&lt;/TT&gt;:&lt;/P&gt;&lt;P&gt;

         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; AC_REVISION($Revision: 1.1 $)dnl
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/P&gt;&lt;P&gt;

          produces this in &lt;CODE&gt;configure&lt;/CODE&gt;:&lt;/P&gt;&lt;P&gt;

         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; #! /bin/sh # From configure.in
         Revision: 1.30 &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;
        </synopsis>
  </macro>
  <macro id="AC_DECL_YYTEXT">
      <prototype>
      </prototype>
        <synopsis>
            Define &lt;CODE&gt;YYTEXT_POINTER&lt;/CODE&gt; if
         &lt;CODE&gt;yytext&lt;/CODE&gt; is a &lt;samp&gt;char
         *&lt;/samp&gt; instead of a &lt;samp&gt;char []&lt;/samp&gt;. 
         Also set output variable
         &lt;CODE&gt;LEX_OUTPUT_ROOT&lt;/CODE&gt; to the base of the file
         name that the lexer generates; usually
         &lt;TT&gt;lex.yy&lt;/TT&gt;, but sometimes something else. 
         These results vary according to whether
         &lt;CODE&gt;lex&lt;/CODE&gt; or &lt;CODE&gt;flex&lt;/CODE&gt; is
         being used.
        </synopsis>
  </macro>
  <macro id="AC_PROG_AWK">
      <prototype>
      </prototype>
        <synopsis>
           Check for &lt;CODE&gt;mawk&lt;/CODE&gt;,
         &lt;CODE&gt;gawk&lt;/CODE&gt;, &lt;CODE&gt;nawk&lt;/CODE&gt;,
         and &lt;CODE&gt;awk&lt;/CODE&gt;, in that order, and set output
         variable &lt;CODE&gt;AWK&lt;/CODE&gt; to the first one that it
         finds.  It tries &lt;CODE&gt;mawk&lt;/CODE&gt; first because
         that is reported to be the fastest implementation.
        </synopsis>
  </macro>
  <macro id="AC_PROG_CC">
      <prototype>
      </prototype>
        <synopsis>
            Determine a C compiler to use.  If
         &lt;CODE&gt;CC&lt;/CODE&gt; is not already set in the
         environment, check for &lt;CODE&gt;gcc&lt;/CODE&gt;, and use
         &lt;CODE&gt;cc&lt;/CODE&gt; if that's not found. Set output
         variable &lt;CODE&gt;CC&lt;/CODE&gt; to the name of the compiler
         found.&lt;/P&gt;&lt;P&gt;

         If using the GNU C compiler, set shell variable
         &lt;CODE&gt;GCC&lt;/CODE&gt; to &lt;samp&gt;yes&lt;/samp&gt;,
         empty otherwise.  If output variable
         &lt;CODE&gt;CFLAGS&lt;/CODE&gt; was not already set, set it to
         &lt;samp&gt;-g -O2&lt;/samp&gt; for the GNU C compiler
         (&lt;samp&gt;-O2&lt;/samp&gt; on systems where GCC does not
         accept &lt;samp&gt;-g&lt;/samp&gt;), or
         &lt;samp&gt;-g&lt;/samp&gt; for other compilers.&lt;/P&gt;&lt;P&gt;

         If the C compiler being used does not produce executables that
         can run on the system where &lt;CODE&gt;configure&lt;/CODE&gt;
         is being run, set the shell variable
         &lt;CODE&gt;cross_compiling&lt;/CODE&gt; to
         &lt;samp&gt;yes&lt;/samp&gt;, otherwise
         &lt;samp&gt;no&lt;/samp&gt;. In other words, this tests whether
         the build system type is different from the host system type
         (the target system type is irrelevant to this test).  , for more
         on support for cross compiling.
        </synopsis>
  </macro>
  <macro id="AC_PROG_CC_C_O">
      <prototype>
      </prototype>
        <synopsis>
           If the C compiler does not accept the
         &lt;samp&gt;-c&lt;/samp&gt; and &lt;samp&gt;-o&lt;/samp&gt;
         options simultaneously, define
         &lt;CODE&gt;NO_MINUS_C_MINUS_O&lt;/CODE&gt;.
        </synopsis>
  </macro>
  <macro id="AC_PROG_CPP">
      <prototype>
      </prototype>
        <synopsis>
           Set output variable &lt;CODE&gt;CPP&lt;/CODE&gt; to a command
         that runs the C preprocessor.  If &lt;samp&gt;$CC
         -E&lt;/samp&gt; doesn't work, it uses
         &lt;TT&gt;/lib/cpp&lt;/TT&gt;. It is only portable to run
         &lt;CODE&gt;CPP&lt;/CODE&gt; on files with a
         &lt;TT&gt;.c&lt;/TT&gt; extension.&lt;/P&gt;&lt;P&gt;

         If the current language is C (Language Choice), many of the
         specific test macros use the value of
         &lt;CODE&gt;CPP&lt;/CODE&gt; indirectly by calling
         &lt;CODE&gt;AC_TRY_CPP&lt;/CODE&gt;,
         &lt;CODE&gt;AC_CHECK_HEADER&lt;/CODE&gt;,
         &lt;CODE&gt;AC_EGREP_HEADER&lt;/CODE&gt;, or
         &lt;CODE&gt;AC_EGREP_CPP&lt;/CODE&gt;.
        </synopsis>
  </macro>
  <macro id="AC_PROG_CXX">
      <prototype>
      </prototype>
        <synopsis>
            Determine a C++ compiler to use.  Check if the environment
         variable &lt;CODE&gt;CXX&lt;/CODE&gt; or
         &lt;CODE&gt;CCC&lt;/CODE&gt; (in that order) is set; if so, set
         output variable &lt;CODE&gt;CXX&lt;/CODE&gt; to its value. 
         Otherwise search for a C++ compiler under likely names
         (&lt;CODE&gt;c++&lt;/CODE&gt;, &lt;CODE&gt;g++&lt;/CODE&gt;,
         &lt;CODE&gt;gcc&lt;/CODE&gt;, &lt;CODE&gt;CC&lt;/CODE&gt;,
         &lt;CODE&gt;cxx&lt;/CODE&gt;, and
         &lt;CODE&gt;cc++&lt;/CODE&gt;).  If none of those checks
         succeed, as a last resort set &lt;CODE&gt;CXX&lt;/CODE&gt; to
         &lt;CODE&gt;gcc&lt;/CODE&gt;.&lt;/P&gt;&lt;P&gt;

         If using the GNU C++ compiler, set shell variable
         &lt;CODE&gt;GXX&lt;/CODE&gt; to &lt;samp&gt;yes&lt;/samp&gt;,
         empty otherwise.  If output variable
         &lt;CODE&gt;CXXFLAGS&lt;/CODE&gt; was not already set, set it to
         &lt;samp&gt;-g -O2&lt;/samp&gt; for the GNU C++ compiler
         (&lt;samp&gt;-O2&lt;/samp&gt; on systems where G++ does not
         accept &lt;samp&gt;-g&lt;/samp&gt;), or
         &lt;samp&gt;-g&lt;/samp&gt; for other compilers.&lt;/P&gt;&lt;P&gt;

         If the C++ compiler being used does not produce executables that
         can run on the system where &lt;CODE&gt;configure&lt;/CODE&gt;
         is being run, set the shell variable
         &lt;CODE&gt;cross_compiling&lt;/CODE&gt; to
         &lt;samp&gt;yes&lt;/samp&gt;, otherwise
         &lt;samp&gt;no&lt;/samp&gt;. In other words, this tests whether
         the build system type is different from the host system type
         (the target system type is irrelevant to this test).  , for more
         on support for cross compiling.
        </synopsis>
  </macro>
  <macro id="AC_PROG_CXXCPP">
      <prototype>
      </prototype>
        <synopsis>
           Set output variable &lt;CODE&gt;CXXCPP&lt;/CODE&gt; to a
         command that runs the C++ preprocessor.  If &lt;samp&gt;$CXX
         -E&lt;/samp&gt; doesn't work, it uses
         &lt;TT&gt;/lib/cpp&lt;/TT&gt;. It is only portable to run
         &lt;CODE&gt;CXXCPP&lt;/CODE&gt; on files with a
         &lt;TT&gt;.c&lt;/TT&gt;, &lt;TT&gt;.C&lt;/TT&gt;, or
         &lt;TT&gt;.cc&lt;/TT&gt; extension.&lt;/P&gt;&lt;P&gt;

         If the current language is C++ (Language Choice), many of the
         specific test macros use the value of
         &lt;CODE&gt;CXXCPP&lt;/CODE&gt; indirectly by calling
         &lt;CODE&gt;AC_TRY_CPP&lt;/CODE&gt;,
         &lt;CODE&gt;AC_CHECK_HEADER&lt;/CODE&gt;,
         &lt;CODE&gt;AC_EGREP_HEADER&lt;/CODE&gt;, or
         &lt;CODE&gt;AC_EGREP_CPP&lt;/CODE&gt;.
        </synopsis>
  </macro>
  <macro id="AC_PROG_F77">
      <prototype>
      </prototype>
        <synopsis>
            Determine a Fortran 77 compiler to use.  If
         &lt;CODE&gt;F77&lt;/CODE&gt; is not already set in the
         environment, check for &lt;CODE&gt;g77&lt;/CODE&gt;,
         &lt;CODE&gt;f77&lt;/CODE&gt; and &lt;CODE&gt;f2c&lt;/CODE&gt;,
         in that order.  Set the output variable
         &lt;CODE&gt;F77&lt;/CODE&gt; to the name of the compiler found.&lt;/P&gt;&lt;P&gt;

         If using &lt;CODE&gt;g77&lt;/CODE&gt; (the GNU Fortran 77
         compiler), then &lt;CODE&gt;AC_PROG_F77&lt;/CODE&gt; will set
         the shell variable &lt;CODE&gt;G77&lt;/CODE&gt; to
         &lt;samp&gt;yes&lt;/samp&gt;, and empty otherwise.  If the
         output variable &lt;CODE&gt;FFLAGS&lt;/CODE&gt; was not already
         set in the environment, then set it to &lt;samp&gt;-g
         -02&lt;/samp&gt; for &lt;CODE&gt;g77&lt;/CODE&gt; (or
         &lt;samp&gt;-O2&lt;/samp&gt; where &lt;CODE&gt;g77&lt;/CODE&gt;
         does not accept &lt;samp&gt;-g&lt;/samp&gt;). Otherwise, set
         &lt;CODE&gt;FFLAGS&lt;/CODE&gt; to &lt;samp&gt;-g&lt;/samp&gt;
         for all other Fortran 77 compilers.
        </synopsis>
  </macro>
  <macro id="AC_PROG_F77_C_O">
      <prototype>
      </prototype>
        <synopsis>
           Test if the Fortran 77 compiler accepts the options
         &lt;samp&gt;-c&lt;/samp&gt; and &lt;samp&gt;-o&lt;/samp&gt;
         simultaneously, and define
         &lt;CODE&gt;F77_NO_MINUS_C_MINUS_O&lt;/CODE&gt; if it does not.
        </synopsis>
  </macro>
  <macro id="AC_PROG_GCC_TRADITIONAL">
      <prototype>
      </prototype>
        <synopsis>
           Add &lt;samp&gt;-traditional&lt;/samp&gt; to output variable
         &lt;CODE&gt;CC&lt;/CODE&gt; if using the GNU C compiler and
         &lt;CODE&gt;ioctl&lt;/CODE&gt; does not work properly without
         &lt;samp&gt;-traditional&lt;/samp&gt;.  That usually happens
         when the fixed header files have not been installed on an old
         system.  Since recent versions of the GNU C compiler fix the
         header files automatically when installed, this is becoming a
         less prevalent problem.
        </synopsis>
  </macro>
  <macro id="AC_PROG_INSTALL">
      <prototype>
      </prototype>
        <synopsis>
              Set output variable &lt;CODE&gt;INSTALL&lt;/CODE&gt; to the
         path of a BSD compatible &lt;CODE&gt;install&lt;/CODE&gt;
         program, if one is found in the current
         &lt;CODE&gt;PATH&lt;/CODE&gt;. Otherwise, set
         &lt;CODE&gt;INSTALL&lt;/CODE&gt; to
         &lt;samp&gt;&lt;VAR&gt;dir&lt;/VAR&gt;/install-sh
         -c&lt;/samp&gt;, checking the directories specified to
         &lt;CODE&gt;AC_CONFIG_AUX_DIR&lt;/CODE&gt; (or its default
         directories) to determine &lt;VAR&gt;dir&lt;/VAR&gt; (Output). 
         Also set the variables &lt;CODE&gt;INSTALL_PROGRAM&lt;/CODE&gt;
         and &lt;CODE&gt;INSTALL_SCRIPT&lt;/CODE&gt; to
         &lt;samp&gt;$INSTALL@&lt;/samp&gt; and
         &lt;CODE&gt;INSTALL_DATA&lt;/CODE&gt; to
         &lt;samp&gt;$INSTALL@&lt;/samp&gt; -m 644.&lt;/P&gt;&lt;P&gt;

         This macro screens out various instances of
         &lt;CODE&gt;install&lt;/CODE&gt; known to not work.  It prefers
         to find a C program rather than a shell script, for speed. 
         Instead of &lt;TT&gt;install-sh&lt;/TT&gt;, it can also use
         &lt;TT&gt;install.sh&lt;/TT&gt;, but that name is obsolete
         because some &lt;CODE&gt;make&lt;/CODE&gt; programs have a rule
         that creates &lt;TT&gt;install&lt;/TT&gt; from it if there is no
         &lt;TT&gt;Makefile&lt;/TT&gt;.&lt;/P&gt;&lt;P&gt;

         A copy of &lt;TT&gt;install-sh&lt;/TT&gt; which you may use
         comes with Autoconf.  If you use
         &lt;CODE&gt;AC_PROG_INSTALL&lt;/CODE&gt;, you must include
         either &lt;TT&gt;install-sh&lt;/TT&gt; or
         &lt;TT&gt;install.sh&lt;/TT&gt; in your distribution, or
         &lt;CODE&gt;configure&lt;/CODE&gt; will produce an error message
         saying it can't find them---even if the system you're on has a
         good &lt;CODE&gt;install&lt;/CODE&gt; program. This check is a
         safety measure to prevent you from accidentally leaving that
         file out, which would prevent your package from installing on
         systems that don't have a BSD-compatible
         &lt;CODE&gt;install&lt;/CODE&gt; program.&lt;/P&gt;&lt;P&gt;

         If you need to use your own installation program because it has
         features not found in standard &lt;CODE&gt;install&lt;/CODE&gt;
         programs, there is no reason to use
         &lt;CODE&gt;AC_PROG_INSTALL&lt;/CODE&gt;; just put the pathname
         of your program into your &lt;TT&gt;Makefile.in&lt;/TT&gt;
         files.
        </synopsis>
  </macro>
  <macro id="AC_PROG_LEX">
      <prototype>
      </prototype>
        <synopsis>
            If &lt;CODE&gt;flex&lt;/CODE&gt; is found, set output
         variable &lt;CODE&gt;LEX&lt;/CODE&gt; to
         &lt;samp&gt;flex&lt;/samp&gt; and
         &lt;CODE&gt;LEXLIB&lt;/CODE&gt; to
         &lt;samp&gt;-lfl&lt;/samp&gt;, if that library is in a standard
         place.  Otherwise set &lt;CODE&gt;LEX&lt;/CODE&gt; to
         &lt;samp&gt;lex&lt;/samp&gt; and &lt;CODE&gt;LEXLIB&lt;/CODE&gt;
         to &lt;samp&gt;-ll&lt;/samp&gt;.
        </synopsis>
  </macro>
  <macro id="AC_PROG_LN_S">
      <prototype>
      </prototype>
        <synopsis>
           If &lt;samp&gt;ln -s&lt;/samp&gt; works on the current
         filesystem (the operating system and filesystem support symbolic
         links), set output variable &lt;CODE&gt;LN_S&lt;/CODE&gt; to
         &lt;samp&gt;ln -s&lt;/samp&gt;, otherwise set it to
         &lt;samp&gt;ln&lt;/samp&gt;.&lt;/P&gt;&lt;P&gt;

         If the link is put in a directory other than the current
         directory, its meaning depends on whether
         &lt;samp&gt;ln&lt;/samp&gt; or &lt;samp&gt;ln -s&lt;/samp&gt; is
         used.  To safely create links using
         &lt;samp&gt;$(LN_S)&lt;/samp&gt;, either find out which form is
         used and adjust the arguments, or always invoke
         &lt;CODE&gt;ln&lt;/CODE&gt; in the directory where the link is
         to be created.&lt;/P&gt;&lt;P&gt;

         In other words, it does not work to do
         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; $(LN_S) foo /x/bar
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/P&gt;&lt;P&gt;

         Instead, do&lt;/P&gt;&lt;P&gt;

         &lt;TABLE&gt;&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;td
         class=example&gt;&lt;pre&gt; (cd /x &amp;&amp; $(LN_S) foo bar)
         &lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;
        </synopsis>
  </macro>
  <macro id="AC_PROG_RANLIB">
      <prototype>
      </prototype>
        <synopsis>
           Set output variable &lt;CODE&gt;RANLIB&lt;/CODE&gt; to
         &lt;samp&gt;ranlib&lt;/samp&gt; if
         &lt;CODE&gt;ranlib&lt;/CODE&gt; is found, otherwise to
         &lt;samp&gt;:&lt;/samp&gt; (do nothing).
        </synopsis>
  </macro>
  <macro id="AC_PROG_YACC">
      <prototype>
      </prototype>
        <synopsis>
           If &lt;CODE&gt;bison&lt;/CODE&gt; is found, set output
         variable &lt;CODE&gt;YACC&lt;/CODE&gt; to &lt;samp&gt;bison
         -y&lt;/samp&gt;.  Otherwise, if &lt;CODE&gt;byacc&lt;/CODE&gt;
         is found, set &lt;CODE&gt;YACC&lt;/CODE&gt; to
         &lt;samp&gt;byacc&lt;/samp&gt;.  Otherwise set
         &lt;CODE&gt;YACC&lt;/CODE&gt; to &lt;samp&gt;yacc&lt;/samp&gt;.
        </synopsis>
  </macro>
  <macro id="AC_CHECK_FILE">
      <prototype>
        <parameter content="file ["/>
        <parameter content="action-if-found ["/>
        <parameter content="action-if-not-found]]"/>
      </prototype>
        <synopsis>
          Check whether file &lt;VAR&gt;file&lt;/VAR&gt; exists on the
         native system. If it is found, execute
         &lt;VAR&gt;action-if-found&lt;/VAR&gt;, otherwise do